# Generated by Django 5.2.1 on 2025-06-20 14:28

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('enrolment', '0002_childcarecenter_enrolment_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolment',
            name='center',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='enrolments',
                to='enrolment.childcarecenter',
                default=None,
                null=True
            ),
        ),
    ]
