# Generated by Django 5.2.1 on 2025-06-20 14:30

from django.db import migrations, models
import django.db.models.deletion

def create_default_center(apps, schema_editor):
    ChildcareCenter = apps.get_model('enrolment', 'ChildcareCenter')
    default_center = ChildcareCenter.objects.create(
        name="Default Childcare Center",
        address="123 Main Street",
        phone_number="555-0123",
        email="info@defaultcenter.com",
        capacity=50,
        is_active=True
    )
    return default_center

def remove_default_center(apps, schema_editor):
    ChildcareCenter = apps.get_model('enrolment', 'ChildcareCenter')
    ChildcareCenter.objects.filter(name="Default Childcare Center").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('enrolment', '0004_auto_20250620_1429'),
    ]

    operations = [
        migrations.RunPython(create_default_center, remove_default_center),
    ]
