# Generated by Django 5.2.1 on 2025-06-20 14:31

from django.db import migrations
import django.db.models.deletion

def set_default_center(apps, schema_editor):
    ChildcareCenter = apps.get_model('enrolment', 'ChildcareCenter')
    Enrolment = apps.get_model('enrolment', 'Enrolment')
    
    # Get the first default center
    default_center = ChildcareCenter.objects.filter(name="Default Childcare Center").first()
    
    if default_center:
        # Update all enrolments to use the default center
        Enrolment.objects.all().update(center=default_center)

def remove_default_center(apps, schema_editor):
    Enrolment = apps.get_model('enrolment', 'Enrolment')
    Enrolment.objects.all().update(center=None)

class Migration(migrations.Migration):

    dependencies = [
        ('enrolment', '0005_auto_20250620_1430'),
    ]

    operations = [
        migrations.RunPython(set_default_center, remove_default_center),
    ]
