# Generated by Django 5.2.1 on 2025-06-20 14:31

from django.db import migrations, models
from django.db.models import deletion

class Migration(migrations.Migration):

    dependencies = [
        ('enrolment', '0006_auto_20250620_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolment',
            name='center',
            field=models.ForeignKey(
                on_delete=deletion.CASCADE,
                related_name='enrolments',
                to='enrolment.childcarecenter',
                null=False
            ),
        ),
    ]
