# Generated by Django 5.2.1 on 2025-06-20 14:42

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('enrolment', '0007_auto_20250620_1431'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolment',
            name='center',
        ),
        migrations.AddField(
            model_name='enrolment',
            name='center',
            field=models.ForeignKey(
                on_delete=models.CASCADE,
                related_name='enrolments',
                to='attendance.center',
                null=True,
                default=None
            ),
        ),
    ]
