# Generated by Django 5.2.1 on 2025-06-20 14:42

from django.db import migrations, models

def set_default_center(apps, schema_editor):
    Enrolment = apps.get_model('enrolment', 'Enrolment')
    Center = apps.get_model('attendance', 'Center')
    
    # Get the first center
    default_center = Center.objects.first()
    
    if default_center:
        # Update all enrolments to use the default center
        Enrolment.objects.all().update(center=default_center)

def remove_default_center(apps, schema_editor):
    Enrolment = apps.get_model('enrolment', 'Enrolment')
    Enrolment.objects.all().update(center=None)

class Migration(migrations.Migration):

    dependencies = [
        ('enrolment', '0008_auto_20250620_1442'),
    ]

    operations = [
        migrations.RunPython(set_default_center, remove_default_center),
        migrations.AlterField(
            model_name='enrolment',
            name='center',
            field=models.ForeignKey(
                on_delete=models.CASCADE,
                related_name='enrolments',
                to='attendance.center',
                null=False
            ),
        ),
    ]
