# Generated by Django 5.2.1 on 2025-06-20 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_teacher_options_teacher_is_admin'),
        ('enrolment', '0009_auto_20250620_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolment',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolments', to='attendance.room'),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to='attendance.child'),
        ),
    ]
