# Generated by Django 5.2.1 on 2025-06-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolment', '0010_enrolment_room_alter_enrolment_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='relationship',
            field=models.CharField(choices=[('parent', 'Parent'), ('grandparent', 'Grandparent'), ('aunt', 'Aunt'), ('uncle', 'Uncle'), ('sibling', 'Sibling'), ('cousin', 'Cousin'), ('family_friend', 'Family Friend'), ('other', 'Other')], max_length=50),
        ),
    ]
