# Generated by Django 5.2.1 on 2025-06-23 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolment', '0011_emergencycontact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalinformation',
            name='allergies',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='medicalinformation',
            name='medical_conditions',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='medicalinformation',
            name='medical_notes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='medicalinformation',
            name='medications',
            field=models.TextField(),
        ),
    ]
