# Generated by Django 5.2.1 on 2025-06-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolment', '0012_alter_medicalinformation_allergies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalinformation',
            name='immunization_record',
            field=models.FileField(blank=True, null=True, upload_to='children/immunization_records/'),
        ),
    ]
