# Generated by Django 5.2.1 on 2025-06-23 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolment', '0013_alter_medicalinformation_immunization_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalinformation',
            name='immunization_record',
            field=models.FileField(blank=True, null=True, upload_to='immunization_records/'),
        ),
    ]
