# Generated by Django 5.2.1 on 2025-05-30 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0010_attendance_late_attendance_late_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('late_sign_in', 'Late Sign In'), ('late_sign_out', 'Late Sign Out'), ('general', 'General Notification')], max_length=20)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='attendance.child')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='attendance.parent')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
