# Generated by Django 5.2.1 on 2025-06-07 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('child', 'sign_in__date'), name='unique_sign_in_per_day'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(condition=models.Q(('sign_out__isnull', True)), fields=('child', 'sign_in'), name='unique_active_sign_in'),
        ),
    ]
