# Generated by Django 5.2.1 on 2025-06-19 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_add_constraints'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendance',
            name='unique_sign_in_per_day',
        ),
    ]
