# Generated by Django 5.2.1 on 2025-05-29 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_child_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/child_pix/'),
        ),
    ]
