# Generated by Django 5.2.1 on 2025-06-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_attendance_unique_sign_in_per_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['-created_at'], 'permissions': [('can_manage_enrolment', 'Can manage child enrolment'), ('can_view_all_children', 'Can view all children in the center'), ('can_manage_teachers', 'Can manage other teachers')]},
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Designates whether this teacher has admin privileges.'),
        ),
    ]
