# Generated by Django 5.2.1 on 2025-05-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_child_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='attendance',
            name='action_type',
            field=models.CharField(choices=[('sign_in', 'Sign In'), ('sign_out', 'Sign Out')], default='sign_in', max_length=10),
        ),
    ]
