# Generated by Django 5.2.1 on 2025-05-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_attendance_options_attendance_action_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('child', 'timestamp'), name='unique_child_attendance_per_day'),
        ),
    ]
