# Generated by Django 5.2.1 on 2025-06-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/teachers/qr_codes/'),
        ),
        migrations.DeleteModel(
            name='QRCode',
        ),
    ]
