# Generated by Django 5.2.1 on 2025-06-22 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_teacher_qr_code_delete_qrcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='qr_code',
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='static/images/qrcodes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_qrcodes', to='attendance.center')),
            ],
        ),
    ]
