# Generated by Django 5.2.1 on 2025-05-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_center_attendance_center_child_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
