# Generated by Django 5.2.1 on 2025-06-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_remove_teacher_qr_code_qrcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='is_active',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='dashboard_url',
            field=models.URLField(default='http://localhost:8000/attendance/dashboard/'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
