# Generated by Django 5.2.1 on 2025-05-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_center_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='emergency_phone',
            field=models.CharField(max_length=20),
        ),
    ]
