# Generated by Django 5.2.1 on 2025-06-07 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_merge_20250606_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='emergency_phone',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='child',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/children/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
