# Generated by Django 5.2.1 on 2025-06-22 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_remove_qrcode_expires_at_remove_qrcode_is_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QRCode',
        ),
    ]
