# Generated by Django 5.2.1 on 2025-06-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_delete_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='children/profiles/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='teachers/profiles/'),
        ),
    ]
