# Generated by Django 5.2.1 on 2025-05-30 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_attendance_late_attendance_late_reason_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendance',
            name='unique_child_attendance_per_day',
        ),
    ]
