# Generated by Django 5.2.1 on 2025-06-23 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_alter_child_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/children/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/teachers/'),
        ),
    ]
