# Generated by Django 5.2.1 on 2025-05-31 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_remove_attendance_unique_child_attendance_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='opening_time',
            field=models.TimeField(default='08:30:00'),
        ),
    ]
