# Generated by Django 5.2.1 on 2025-05-31 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_center_opening_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='prevent_sign_in_until_tomorrow',
            field=models.BooleanField(default=False),
        ),
    ]
