# Generated by Django 5.2.1 on 2025-05-31 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_attendance_prevent_sign_in_until_tomorrow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-sign_in', '-sign_out']},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='action_type',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='late',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='late_reason',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='prevent_sign_in_until_tomorrow',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='attendance',
            name='sign_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='sign_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
