# Generated by Django 5.2.1 on 2025-06-02

from django.db import migrations

def update_model_state(apps, schema_editor):
    # This function will be called during migration but won't make any database changes
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_combined_migration'),
    ]

    operations = [
        migrations.RunPython(update_model_state, migrations.RunPython.noop),
    ]
